controller_manager:
  ros__parameters:
    update_rate: 100

    effort_controller:
      type: forward_command_controller/ForwardCommandController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    

effort_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: effort

joint_state_broadcaster:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
